for (let i = 1; i <= 10; i++){
    console.log(i)
}
// DE FOR LOOP START BIJ 1 EN BLIJFT LOPEN ZOLANG I KLEINER OF GELIJK IS AAN 10?
// WAARBIJ I NA ELKE ITERATIE MET 1 WORDT VERHOOGD
//1,2,3,4,5,6,7,8,9,10
